common_mysql: &common_mysql
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 5
  username: root
  password:
  host: localhost
 
development:
  <<: *common_mysql
  database: marketplace_development
 
test:
  <<: *common_mysql
  database: marketplace_test

production:
  <<: *common_mysql
  database: marketplace_production
